name: 'Claude Code Review'
description: 'Automated code reviews using Claude AI'
author: 'Two Inc'

inputs:
  anthropic_api_key:
    description: 'Anthropic API key for Claude'
    required: true
  track_progress:
    description: 'Enable visual progress tracking comments'
    required: false
    default: 'false'
  use_sticky_comment:
    description: 'Use sticky comments for consistent feedback across PR updates'
    required: false
    default: 'true'
  prompt:
    description: 'Custom review prompt'
    required: false
    default: |
      REPO: ${{ github.repository }}
      PR NUMBER: ${{ github.event.pull_request.number || github.event.issue.number }}

      **Tool Reference** (use MCP tools as primary, GraphQL as fallback or where MCP lacks support):
      - Reading PR details: `mcp__github__get_pull_request`
      - Reading PR comments: `mcp__github__get_issue_comments`
      - Reading review comments: `mcp__github__get_pull_request_review_comments`
      - Reading PR diff: `mcp__github__get_pull_request_diff`
      - Creating top-level PR comment: `mcp__github__add_issue_comment`
      - Creating review with inline comments: `mcp__github__create_and_submit_pull_request_review`
      - **Replying to inline comments**: `Bash(gh api graphql:*)` (MCP does not support this)
      - **Resolving review threads**: `Bash(gh api graphql:*)` with resolveReviewThread mutation (MCP does not support this)
      - General fallback for any failed MCP operation: `Bash(gh api graphql:*)`

      **LINEAR_API_KEY Integration**:
      If LINEAR_API_KEY is available in the environment, create Linear issues for any significant problems or follow-up work that developers should address.

      **STEP 1 - Determine PR Type**:
      First, use `mcp__github__get_pull_request` to read the PR title, description, and branch names to determine if this is a release PR.

      **Release PR Detection**:
      If the PR title, branch name, or description contains patterns like "release", "version", "v[0-9]", "bump", "tag", or if it's merging a release branch to main, treat it as a release PR.

      **For Release PRs**: Create a release summary instead of a detailed review:
      1. **MANDATORY - Check for existing summaries**: Use `mcp__github__get_issue_comments` to read all PR comments and see if a release summary already exists
      2. **NEVER duplicate summaries**: If a release summary comment already exists, DO NOT create another one
      3. **Create release summary**: Use `mcp__github__add_issue_comment` to post a single comprehensive release summary covering:
         - Key features and changes
         - Breaking changes or migrations needed
         - Notable bug fixes
         - Dependencies or version updates
         - Any security improvements
      4. **Do NOT create a review**: Skip the normal review process entirely

      **For Regular PRs**: Follow normal review process with extreme selectivity:
      1. **MANDATORY - Read ALL existing comments FIRST**: Use `mcp__github__get_pull_request_review_comments` to read ALL existing review comments and threads from Claude and other reviewers BEFORE starting anything
      2. **Get diff information**: Use `mcp__github__get_pull_request_diff` to understand the code changes and line numbers
      3. **Cross-reference with existing comments**: Before making ANY comment, check if the same issue has already been raised by Claude or any other reviewer in previous comments
      4. **Create and submit review**: Use `mcp__github__create_and_submit_pull_request_review` to create a review with inline comments ONLY for critical issues that have NOT been previously mentioned
         - If you have critical comments: Submit with event type "COMMENT" and include inline comments on specific lines
         - If no critical issues found: Submit with event type "APPROVE" to approve the PR
      5. **Resolve fixed issues**: If any issues you previously raised have been fixed, use `Bash(gh api graphql:*)` with resolveReviewThread mutation to resolve those threads

      **ONLY comment on these critical issues:**
      - **Security vulnerabilities** (SQL injection, XSS, authentication bypasses, etc.)
      - **Critical bugs** that will cause runtime failures, data corruption, or crashes
      - **Memory leaks** or severe performance bottlenecks
      - **Breaking API changes** that will break existing functionality
      - **Data loss risks** or unsafe database operations

      **DO NOT comment on:**
      - Minor style issues or formatting
      - Subjective code organisation preferences
      - Non-critical performance optimisations
      - Minor refactoring suggestions
      - Documentation improvements
      - Variable naming (unless genuinely confusing)
      - Code that works correctly but could be "better"

      **Rules:**
      - **NEVER duplicate existing comments**: If Claude or any other reviewer has already mentioned an issue, DO NOT comment on it again
      - **AVOID top-level comments**: Always prefer inline comments on specific lines. Only use top-level PR comments for release summaries or overall PR concerns that cannot be tied to specific code lines
      - **Always resolve fixed issues**: If you previously raised an issue in an earlier commit and it has been fixed in a follow-up commit, you MUST resolve that thread
      - If unsure whether an issue is critical enough, DON'T comment
      - If unsure whether an issue has already been raised, DON'T comment
      - Maximum 3 comments per PR unless there are genuine security/critical issues
      - Each comment must identify a specific, actionable problem that risks system stability, security, or data integrity
      - If no NEW critical issues found (beyond what's already been commented), approve the PR instead of leaving comments
  extra_prompt:
    description: 'Additional instructions to append to the base prompt'
    required: false
    default: ''
  claude_args:
    description: 'Additional Claude CLI arguments'
    required: false
    default: '--allowedTools "mcp__github__get_pull_request,mcp__github__get_issue_comments,mcp__github__get_pull_request_diff,mcp__github__get_pull_request_review_comments,mcp__github__create_and_submit_pull_request_review,mcp__github__add_issue_comment,Bash(gh api graphql:*)"'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Setup GitHub CLI
      shell: bash
      run: |
        if ! command -v gh &> /dev/null; then
          echo "Installing GitHub CLI..."
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh -y
        fi
        gh --version

    - name: Run Claude Code Review
      uses: anthropics/claude-code-action@v1
      with:
        anthropic_api_key: ${{ inputs.anthropic_api_key }}
        track_progress: ${{ inputs.track_progress }}
        use_sticky_comment: ${{ inputs.use_sticky_comment }}
        prompt: |
          ${{ inputs.prompt }}

          ${{ inputs.extra_prompt }}
        claude_args: ${{ inputs.claude_args }}
